export const ADD_COMMENT = 'ADD_COMMENT';
export const EXAMS_LOADING = 'DISHES_LOADING';
export const EXAMS_FAILED = 'DISHES_FAILED';
export const ADD_EXAMS = 'ADD_DISHES';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';